# Generated by Django 5.0.6 on 2024-08-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_address_delivery_location_delivery_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
