# Generated by Django 5.0.6 on 2024-08-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
