# Generated by Django 5.0.6 on 2024-08-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_offer_model',
            old_name='food_itme',
            new_name='food_item',
        ),
    ]
