# Generated by Django 5.0.6 on 2024-08-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_food_itme_special_offer_model_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item_model',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
