# Generated by Django 5.0.6 on 2024-08-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_food_item_model_category_delete_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='menu/category_logo/')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AddField(
            model_name='food_item_model',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='menu.categorymodel'),
        ),
    ]
