# Generated by Django 5.0.6 on 2024-10-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_product_image'),
        ('orders', '0002_remove_orders_cart_remove_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='special_offer_model',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Special_Offer_Model',
        ),
    ]
