# Generated by Django 5.0.6 on 2024-08-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
   
        ('orders', '0011_remove_order_food_item_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item_model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='special_offer_model',
            name='food_item',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='Food_item_Model',
        ),
        migrations.DeleteModel(
            name='Special_Offer_Model',
        ),
    ]
