# Generated by Django 5.0.6 on 2024-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
    ]
