# Generated by Django 5.0.6 on 2024-08-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_reviewmodel_options_reviewmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
