# Generated by Django 5.0.6 on 2024-08-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_reviewmodel_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
