# Generated by Django 5.0.6 on 2024-08-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_itemmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_itemmodel',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart_ItemModel',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_ItemModel',
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
