# Generated by Django 5.0.6 on 2024-08-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='deivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
