# Generated by Django 5.0.6 on 2024-08-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
