# Generated by Django 5.0.6 on 2024-08-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_initial'),
        ('orders', '0014_orders_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='deivery_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='deivery_permission',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.PROTECT, to='delivery.delivery'),
        ),
    ]
