# Generated by Django 5.0.6 on 2024-08-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orders_deivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='deivery_permission',
        ),
    ]
