# Generated by Django 5.0.6 on 2024-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
