# Generated by Django 5.0.6 on 2024-08-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
