# Generated by Django 5.0.6 on 2024-08-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_orderitem_price_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
