# Generated by Django 5.0.6 on 2024-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_orders_product_remove_orders_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
