# Generated by Django 5.0.6 on 2024-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orders_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
